### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by bkeepers** [bkeepers/strappydoo#13]
I'd love to have python support so someone could clone a typical Django project and run `strappy bootstrap`, `strappy server`, `strappy test`, and `strappy console` and have the project running without any further knowledge of Python.

- [ ] Pip (see [bundler](https://github.com/bkeepers/strappydoo/blob/master/plugins/3-bundler.sh) for inspiration)
- [ ] Django (see [rails](https://github.com/bkeepers/strappydoo/blob/master/plugins/3-rails.sh) for inspiration)
- [ ] … what else?

See the [docs](https://github.com/bkeepers/strappydoo#adding-new-plugins) for more info on defining new languages & frameworks.

**Comment by jacebrowning** [comment]
Bootstrap:

- `.python-version` => Use `pyenv` for to install Python
- `requirements.txt` => Use `pip` to install dependencies
- `Pipfile` => Use `pipenv` to install dependencies

Server:

- `manage.py` => This project _might_ be Django: `python manage.py runserver`

Test:

- `manage.py` => This project _might_ be Django: `python manage.py test`
- `pytest.ini` => Call `pytest` to run tests instead?

Console:

- `manage.py` => This project _might_ be Django: `python manage.py shell`
