### ISSUE TITLE
README reads `Scrappydoo` not `Strappydoo`

### ISSUE THREAD

**Issue by JasonEtco** [bkeepers/strappydoo#20]
A section of the README reads `Scrappydoo` instead of the true excellence that is `Strappydoo` (note the c/t switch). From the README's [**Adding new plugins**](https://github.com/bkeepers/strappydoo/blob/master/README.md#adding-new-plugins) section:

```shell
# Test if Scrappyfile exists or return 1 to disable this plugin
test -f Scrappyfile || return 1

# Now define a function called `${framework}_${command}` that runs the relevant command for each of:
#
# - bootstrap
# - server
# - console
# - test

scrappy_bootstrap() {
  run scrappy install
}
scrappy_server() {
  run scrappy start
}
scrappy_console() {
  run scrappy term
}
scrappy_test() {
  run scrappy test
}
```

**Comment by bkeepers** [comment]
This was intentional. From just above that:

> Here's an example for a fictional framework called `scrappy`, defined in `plugins/3-scrappy.sh`

But happy to switch to a different example if that is confusing. How about `shaggy`?

**Comment by JasonEtco** [comment]
Ahhh - helps to read things I suppose. I jumped to conclusions because of the close similarity in names; `shaggy` would certainly help alleviate that.
